# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: risattou <risattou@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/08/21 19:23:56 by risattou          #+#    #+#              #
#    Updated: 2025/08/21 19:23:57 by risattou         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = megaphone
CC = c++
CFLAGS = -Wall -Wextra -Werror -std=c++98
all: $(NAME)
	CC $(CFLAGS) -c megaphone.cpp -o megaphone.o
$(NAME): megaphone.o
